# See: https://discordapp.com/developers/applications/me for more information on generating a token and bot user

discord_token: ''
discord_application_id: ''
discord_owner_id: ''

command_prefix: '!'

Plugins: 
  - Core
  - SuperSimplePlugin
